config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:edit, :update, :delete] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: 'Is already in the list' }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @bookmarks = @list.bookmarks
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5ec5165f4f.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1 class='h-36 flex items-center justify-center text-gray-50'>WHAT ARE WE WATCHING TONIGHT ?</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back to homepage', lists_path %>

app/views/lists/show.html.erb
  <h1 class='h-36 flex items-center justify-center text-gray-50'><%= @list.name.upcase %></h1>

    <div>
      <div>
        <ul class='list-none p-0 grid grid-cols-1 md:grid-cols-2 lg:grid cols-3 gap-2'>
          <% @list.bookmarks.each do |bookmark| %>
            <li class='flex flex-col self-stretch w-80 h-96 m-auto border-2 rounded-lg shadow-xl'>
              <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title, class: 'rounded-t-md' %>
                <div class='m-2 h-full flex flex-col flex-stretch'>
                  <div class='flex justify-between'>
                    <h5><%= bookmark.movie.title %></h5>
                    <p>Rating : <%= bookmark.movie.rating %>/10</p>
                  </div>
                  <p class='grow text-xs'><%= bookmark.movie.overview %></p>
                  <p class='text-xs font-extrabold'><%= bookmark.comment %></p>
                  <%= link_to 'Delete', bookmark_path(bookmark), method: :delete, class: 'place-self-end p-2 no-underline border rounded-lg bg-indigo-900 text-white text-xs' %>
                </div>
            </li>
          <% end %>
        </ul>
      </div>
      <div class='w-50 flex flex-col items-center m-auto'>
          <h2>Add a bookmark</h2>
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.association :movie, prompt: 'Select a movie', input_html: { data: {controller: 'select2'}} %>
            <%= f.input :comment, placeholder: "Add your comment." %>
            <%= f.submit %>
          <% end %>
      </div>

    <%= link_to 'Back to homepage', lists_path %>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <i class="fa-solid fa-film"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create a list", new_list_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> %>
              <%# <%= link_to "Action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%# </div> %>
          <%# </li> %>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>